version: 2

jobs:
  deploy_subgraph:
    working_directory: ~/dao-subgraph
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout
      - run:
          name: Install yarn
          command: |
            sudo npm install -g yarn
      - run:
          name: Instal Graph CLI
          command: |
            sudo yarn global add @graphprotocol/graph-cli
      - run:
          name: Install dependencies
          command: |
            sudo yarn install
            sudo yarn codegen
      - run:
          name: Deploy the subgraph
          command: |
            sudo graph auth https://api.thegraph.com/deploy/ $ACCESS_TOKEN
            sudo yarn deploy
      - run:
          name: Announce Deployment
          command: |
            chmod +x .circleci/announceDeployment.sh
            .circleci/announceDeployment.sh

workflows:
  version: 2
  deploy_subgraph:
    jobs:
      - deploy_subgraph:
          filters:
            branches:
              only:
                  - master